config/routes.rb
Rails.application.routes.draw do
 root 'dogs#index'
 resources :dogs
 get 'test' => 'dogs#test'
 get 'shelter' => 'dog#shelter'
 get 'shelter/:bla' => 'shelter#show'
 resources :maps
end

#   Prefix Verb   URI Pattern              Controller#Action
#     root GET    /                        dogs#index
#     dogs GET    /dogs(.:format)          dogs#index
#          POST   /dogs(.:format)          dogs#create
#  new_dog GET    /dogs/new(.:format)      dogs#new
# edit_dog GET    /dogs/:id/edit(.:format) dogs#edit
#      dog GET    /dogs/:id(.:format)      dogs#show
#          PATCH  /dogs/:id(.:format)      dogs#update
#          PUT    /dogs/:id(.:format)      dogs#update
#          DELETE /dogs/:id(.:format)      dogs#destroy
#     test GET    /test(.:format)          dogs#test
#  shelter GET    /shelter(.:format)       dog#shelter
#          GET    /shelter/:bla(.:format)  shelter#show
#     maps GET    /maps(.:format)          maps#index
#          POST   /maps(.:format)          maps#create
#  new_map GET    /maps/new(.:format)      maps#new
# edit_map GET    /maps/:id/edit(.:format) maps#edit
#      map GET    /maps/:id(.:format)      maps#show
#          PATCH  /maps/:id(.:format)      maps#update
#          PUT    /maps/:id(.:format)      maps#update
#          DELETE /maps/:id(.:format)      maps#destroy

app/models/coordinate.rb
class Coordinate < ActiveRecord::Base
end

app/models/dog.rb
class Dog < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/coordinates_controller.rb
class CoordinatesController < ApplicationController

	def index
	@coordinates = Coordinate.all
@geojson = Array.new

@coordinates.each do |place|
  @geojson << {
    type: 'Feature',
    geometry: {
      type: 'Point',
      coordinates: [place.longitude, happy_hour.latitude]
    },
    properties: {
      name: place.name,
      address: place.street,
      :'marker-color' => '#00607d',
      :'marker-symbol' => 'circle',
      :'marker-size' => 'medium'
    }
  }
end
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController

	def index
		puts "=============="
		p $petfinder
		puts "=============="
		@pets = $petfinder.find_pets('dog', '11211', count:20) #add option like this.... age:'baby'
		puts @pets.count
		@pets#picture
		puts "***************************"
		puts "****    @pets is   ********"
		p @pets
		puts "***************************"

		@pets.each do |dog|
			Dog.find_or_create_by(name:dog.name, 
				age:dog.age, 
				gender:dog.sex, 
				contact:dog.contact,
				breeds: dog.breeds.each do |breed|
					breed
				end

				)


		end

	end

	def show
		@dog = $petfinder.pet(params[:id])

		@bla = @dog.shelter_id
puts "==============="
		puts @shelter_id
		puts @shelter_id.class
puts "==============="
		puts "==============="
		p @dog
		puts @dog.class
		puts "==============="

		# @breeds = $petfinder.breed('dog')

	end

	def test
		@pets = $petfinder.find_pets('dog', '11211', count:20)
		
	end

	def shelter
		@shelter = $petfinder.shelter(params[:id])

	end

	private

	def dog_params
		params.require(:dog).permit(:name, :id, :shelter_id)
	end
	
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController

	def index
		@map = Map.all
	end
end

app/controllers/shelter_controller.rb
class ShelterController < ApplicationController

	def show
		# @dog = $petfinder.pet('31564331')

		@shelter = $petfinder.shelter(params[:id])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coordinates_helper.rb
module CoordinatesHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/views/dogs/index.html.erb
<h1>DOGS INDEX PAGE</h1>



<% @pets.each do |dog| %>
	<p>
	NAME: <%= dog.name %><br>
	AGE: <%= dog.age %><br>
	ID: <%= dog.id %><br>
	SEX: <%= dog.sex %><br>
	MIX: <%= dog.mix %><br>
	SHELTERID: <%= dog.shelter_id %><br>
	EMAIL: <%= dog.contact %><br>
	STATUS: <%= dog.status %><br>
	ANIMAL: <%= dog.animal %>
	<br>
	SIZE: <%= dog.size %>
	<br>
	<span> PHOTO: <%#= dog.photo %> </span>
	<br>
	<b>TEST: <%#= dog.media[1] %>
	<%= dog.contact %>
	</b>
	<br>
	LAST UDPATED:
	<%= dog.last_update %>
	<br>
	ALL BREEDS? <%= dog.breeds %>
	<br>
	<br>
	CAN WE ITERATE BREEDS? <br>
	<% dog.breeds.each do |this| %>
	<%= this %><br>
	<% end %>
	<br>
	<span><a>BREED:::FIRST BREED IN BREED ARRAY</a><%= dog.breeds[0] %></span>
	<%#= dog.media.photos.photo(1) %> <br>
	///////////////////////////<br>
	///////@photos is////////<br>
	<%#= dog.pictures %>
	<%= @large %><br>
	//////////////////////////
	<br>
<br>
	<%= link_to "SHOW PAGE", dog_path(dog.id) %>
	<br>
	<%= link_to "LOCATION PAGE", shelter_path(dog.shelter_id) %>
	</p>
<% end %>

<h2>PUPS IS</h2>
<%= @pups %>
<hr>
PUP 1
<%# @pups each do |dog| %>
<%#= dog.name %>
<%# end %>

<hr>
@pets [1] is
<%#= @pets[1].media %>

app/views/dogs/sheleter.html.erb
<h1>Shelter page within Dogs View Folder</h1>

<%= @shelter %>

app/views/dogs/show.html.erb
<h1>DOG SHOW PAGE</h1>

<%= @dog.name %>
<br>

<%= @dog.shelter_id %>
<br>

<p>
	<%#= link_to "GET SHELTER ADDRESS", shelters_path('NY805') %>
	<!-- <%= link_to "GET SHELTER ADDRESS", shelter_path(@bla) %> -->
	<%= link_to "GET SHELTER ADDRESS", "/shelter/#{@bla}" %>

</p>

<p>
	DOG BREEDS ARE:
	<%= @breeds %>
</p>

app/views/dogs/test.html.erb
<h1>DOGS INDEX PAGE</h1>



<% @pets.each do |dog| %>
	<p>
	NAME: <%= dog.name %><br>
	AGE: <%= dog.age %><br>
	ID: <%= dog.id %><br>
	SEX: <%= dog.sex %><br>
	MIX: <%= dog.mix %><br>
	SHELTERID: <%= dog.shelter_id %><br>
	EMAIL: <%= dog.contact %><br>
	STATUS: <%= dog.status %><br>
	ANIMAL: <%= dog.animal %>
	<br>
	SIZE: <%= dog.size %>
	<br>
	<span> PHOTO: <%#= dog.photo %> </span>
	<br>
	<b>TEST: <%#= dog.media[1] %>
	<%= dog.contact %>
	</b>
	<br>
	LAST UDPATED:
	<%= dog.last_update %>
	<br>
	ALL BREEDS? <%= dog.breeds %>
	<br>
	<br>
	CAN WE ITERATE BREEDS? <br>
	<% dog.breeds.each do |this| %>
	<%= this %><br>
	<% end %>
	<br>
	<span><a>BREED:::FIRST BREED IN BREED ARRAY</a><%= dog.breeds[0] %></span>
	<%#= dog.media.photos.photo(1) %> <br>
	///////////////////////////<br>
	///////@photos is////////<br>
	<%#= dog.pictures %>
	<%= @large %><br>
	//////////////////////////
	<br>
<br>
	<%= link_to "SHOW PAGE", dog_path(dog.id) %>
	<br>
	<%= link_to "LOCATION PAGE", shelter_path(dog.shelter_id) %>
	</p>
<% end %>

<h2>PUPS IS</h2>
<%= @pups %>
<hr>
PUP 1
<%# @pups each do |dog| %>
<%#= dog.name %>
<%# end %>

<hr>
@pets [1] is
<%#= @pets[1].media %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pawmarkr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shelter/show.html.erb
<h1>Shelter Show page within shelter folder</h1>

		<%= @shelter %>